
      
name: TEST

on: [push]

jobs:     
 sast_scan:
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json -vv

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json
 
 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Build Docker Image
     run: docker build -f Dockerfile -t hameedakshal/hanabi-py:$GITHUB_RUN_NUMBER .

   - name: Docker Scout Scan
     run: |
       curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
       script -q -e -c "bash install-scout.sh" /dev/null

       echo ${{secrets.REPO_PASSWORD}} | docker login -u ${{secrets.REPO_USER}} --password-stdin

       docker scout quickview

       docker scout cves 2> error_list.txt

   - name: Upload Error List Artifact
     uses: actions/upload-artifact@v3
     with:
       name: error-list
       path: error_list.txt

 push:
  name: Build Image and Push Image 
  runs-on: ubuntu-latest
  needs: image_scan

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Build and Push Docker Image with build tag
     run: |
      docker build -f Dockerfile -t hameedakshal/hanabi-py:$GITHUB_RUN_NUMBER .
      echo ${{secrets.REPO_PASSWORD}} | docker login -u ${{secrets.REPO_USER}} --password-stdin
      docker push  hameedakshal/hanabi-py:$GITHUB_RUN_NUMBER
     
   - name: Tag and Push Docker Image with latest tag
     run: |
      echo ${{secrets.REPO_PASSWORD}} | docker login -u ${{secrets.REPO_USER}} --password-stdin
      docker tag  hameedakshal/hanabi-py:$GITHUB_RUN_NUMBER hameedakshal/hanabi-py:latest
      docker push hameedakshal/hanabi-py:latest

  
 deploy:
  name: deploy to ebs
  runs-on: ubuntu-latest
  needs: push

  env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install AWS CLI and Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          sudo apt-get install -y python3-pip
          python -m pip install --upgrade pip
          pip install awsebcli
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -r us-east-1 -p docker Hanabi-demo
          eb deploy Hanabi-demo-env 


   
 
    
   


   
